### PR TITLE
Check (this.target) before calling window.getComputedStyle

### PR DESCRIPTION
**Pull request by pengjoshua**
Hi @xiaody, really nice line-clamping library!

I've been using it my application and it works great, but since I am using some dynamically rendered components, I'm failing some unit tests whenever this.target is undefined or null and window.getComputedStyle(this.target) is called. 

I just added a simple check.

### CODE REVIEW

**Comment by xiaody** [comment]
I wonder in what conditions would `this.target` be undefined or null?

**Comment by pengjoshua** [comment]
Hey @xiaody, thanks for your reply!

I'm conditionally rendering your `ResponsiveHOC`component in my application. If the condition is not satisfied, I am rendering and returning `null`. 

In my unit tests, I'm also rendering mock components without styles or stylesheets which is generating errors with `window.getComputedStyle(this.target)`

**Comment by xiaody** [comment]
I still don't get the point. It would be helpful if you provide a reproduction.

**Comment by xiaody** [comment]
Closed due to inactivity.

**Pull request closed without merging**
