### PR TITLE
Added Aria-Hidden prop to canvas

### PR DESCRIPTION
**Pull request by jm5967a**
- Added aria hidden to canvas
- sorted props alphabetically 

@xiaody

### CODE REVIEW

**Comment by dsbhakta** [comment]
@xiaody 
2. `aria-hidden=false` should be always. ADA is required if it is used in heading, footer tags.

**Comment by jm5967a** [comment]
1. The canvas is made out of a div, which we are applying aria-hidden similar to how it is working with className.

2.  @dsbhakta  answer above. 

3. We are only using index.js at the moment, but I will add.

**Comment by xiaody** [comment]
@jm5967a Let's just drop the prop and make it always true.

**Comment by jm5967a** [comment]
@xiaody I went ahead and removed the props and added aria hidden to both html.js and index.js

**Comment by xiaody** [comment]
LGTM. Thanks again @jm5967a.

**Comment by xiaody** [comment]
I will release a new version this weekend.

**Pull request merged**
